// export {x}         // will throw error
let third = 30;
const fourth = 40;

export {third, fourth}


export default function () {
    console.log('inside export2')
}
